[package]
name = "double-buffer"
description = "A simple double buffer generic implementation"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/jhg/double-buffer-rs"
